name: Typos Check

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@master
